<style>
	:root {
		--FI_has-gutters: true;
		--fl-row-gap: 0px;
		--fl-column-gap: 0px;
	}

	body {
		padding: 2em;
		font-family: sans-serif;
	}

	.page {
		max-width: 50em;
		margin-left: auto;
		margin-right: auto;
	}

	.outline {
		display: flow-root;
		position: relative;
		margin-bottom: 4em;

		&::after {
			content: '';
			display: block;
			position: absolute;
			top: -1px;
			bottom: -1px;
			left: -1px;
			right: -1px;
			border: 1px dotted black;
			pointer-events: none;
		}
	}

	.container {
		padding: 0 !important;
		background: transparent !important;
		font-size: 13px;

		& > {
			& * {
				box-sizing: border-box;
				background: pink;
				border-radius: 5px;
				padding: 1em;
				font-weight: bold;
			}

			& .container > * {
				background: aqua;
			}

			& .container > .container > * {
				background: lightgrey;
			}

			& .container > .container > .container > * {
				background: yellow;
			}
		}
	}

	.flex-wrap {
		flex-wrap: wrap;
	}

	.gap-20px {
		display: flex;
		--gap: 20px;
		gap: var(--gap);

	}

	.gap-40px {
		display: flex;
		gap: 40px;
	}

	.gap-3\% {
		display: flex;
		gap: 3%;
	}

	.gap-6\% {
		display: flex;
		gap: 6%;
	}

	.gap-2em {
		display: flex;
		gap: 2em;
	}

	.gap-20px.margin-20px {
		display: flex;
		gap: 20px;
		margin: 20px;
	}

	.space-evenly {
		justify-content: space-evenly;
	}

	.justify-flex-end {
		justify-content: flex-end;
	}

	.grow {
		flex-grow: 1;
	}

	.item-50\% {
		width: calc(50% - var(--gap));
	}
</style>

<div class="page">

	<h1>Flex Gap Polyfill</h1>

	<p>Below are a list of test cases demonstrating scenarios this polyfill works with.</p>
	<p>View on <a href="https://github.com/limitlessloop/flex-gap-polyfill">github</a>.</p>

	<h4>Basic</h4>
	<pre>
.container {
	display: flex;
	flex-wrap: wrap;
	gap: 20px;
}
	</pre>

	<div class="outline">
		<div class="container gap-20px flex-wrap">
			<div>One</div>
			<div>Two</div>
			<div>Three</div>
			<div>Four</div>
			<div>Five</div>
		</div>
	</div>

	<h3>Nested</h3>

	<pre>
.container {
	display: flex;
	gap: 20px;
	flex-wrap: wrap;
}

.container .container {
	display: flex;
	flex-wrap: wrap;
	gap: 40px;
}
	</pre>

	<div class="outline">
		<div class="container gap-40px flex-wrap">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
			<div class="container gap-20px flex-wrap">
				<div>A</div>
				<div>B</div>
				<div>C</div>
				<div>D</div>
			</div>
		</div>
	</div>

	<h3>Percentages</h3>

	<p>(Percentage row gaps only appear when height is specified, disabled in polyfill for now).</p>

	<pre>
.container
	display: flex;
	flex-wrap: wrap;
	gap: 6%;
}
	</pre>

	<div class="outline">
		<div class="container gap-6% flex-wrap">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
		</div>
	</div>

		<h3>Ems</h3>

	<pre>
.container
	display: flex;
	flex-wrap: wrap;
	gap: 2em;
}
	</pre>

	<div class="outline">
		<div class="container gap-2em flex-wrap">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
		</div>
	</div>

	<h3>Nested Combination (% > px, px > %, em > px, etc)</h3>

	<pre>
.container
	display: flex;
	flex-wrap: wrap;
	gap: 6%;
}

.container .container {
	display: flex;
	flex-wrap: wrap;
	gap: 20px;
}
	</pre>

	<div class="outline">
		<div class="container gap-6% flex-wrap">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
			<div class="container gap-20px flex-wrap">
				<div>A</div>
				<div>B</div>
				<div>C</div>
				<div>D</div>
			</div>
		</div>
	</div>

	<h3>Margin + Gap</h3>

	<pre>
.container
	display: flex;
	flex-wrap: wrap;
	margin: 20px;
	gap: 3%;
}
	</pre>

	<div class="outline">
		<div class="container gap-20px margin-20px flex-wrap">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
		</div>
	</div>

	<h3>Justify End</h3>

	<pre>
.container
	display: flex;
	flex-wrap: wrap;
	justify-content: flex-end;
	gap: 3%;
}
	</pre>

	<div class="outline">
		<div class="container gap-40px flex-wrap space-evenly justify-flex-end">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
		</div>
	</div>

	<h3>Space Evenly</h3>

	<pre>
.container
	display: flex;
	flex-wrap: wrap;
	gap: 3%;
	justify-content: space-evenly;
}
	</pre>

	<div class="outline">
		<div class="container gap-40px flex-wrap space-evenly">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
		</div>
	</div>

	<h3>Grid</h3>

	<pre>
.container {
	display: flex;
	flex-wrap: wrap;
	flex-grow: 1;
	--gap: 20px;
	gap: var(--gap);
}

.item-50% {
	width: calc(50% - var(--gap))
}
	</pre>

	<div class="outline">
		<div class="container gap-20px flex-wrap grow">
			<div class="item-50%">A</div>
			<div class="item-50%">B</div>
			<div class="item-50%">C</div>
			<div class="item-50%">D</div>
		</div>
	</div>

</div>

