<style>
	:root {
		--FI_has-gutters: true;
		--fl-row-gap: 0px;
		--fl-column-gap: 0px;
	}

	body {
		padding: 100px;
		font-family: sans-serif;
	}

	.outline {
		outline: 1px dotted black;
		display: flow-root;
		position: relative;

		/* & ::after {
			content: '';
			display: block;
			position: absolute;
			top: -1px;
			bottom: -1px;
			left: -1px;
			right: -1px;
			border: 1px dotted black;
		} */
	}

	.example {
		padding: 0 !important;
		background: transparent !important;

		& > {
			& * {
				box-sizing: border-box;
				background: pink;
				border-radius: 5px;
				padding: 1em;
				font-size: 13px;
				font-weight: bold;
			}

			& .example > * {
				background: aqua;
			}

			& .example > .example > * {
				background: lightgrey;
			}

			& .example > .example > .example > * {
				background: yellow;
			}
		}
	}

	.flex-wrap {
		flex-wrap: wrap;
	}

	.gap-20px {
		display: flex;
		gap: 20px;
	}

	.gap-40px {
		display: flex;
		gap: 40px;
	}

	.gap-3\% {
		display: flex;
		gap: 3%;
	}

	.gap-6\% {
		display: flex;
		gap: 6%;
	}
</style>

<h1>Flex Gap Polyfill</p>

<h4>Basic</h4>
<pre>
.example {
	display: flex;
	flex-wrap: wrap;
	gap: 20px;
}
</pre>

<div class="outline">
	<div class="example gap-20px flex-wrap">
		<div><a href="/">One</a></div>
		<div>Two</div>
		<div>Three</div>
		<div>Four</div>
		<div>Five</div>
	</div>
</div>

<h4>Nested</h4>

<pre>
.example {
	display: flex;
	gap: 20px;
	flex-wrap: wrap;
}

.example .example {
	display: flex;
	flex-wrap: wrap;
	gap: 40px;
}
</pre>

<div class="outline">
	<div class="example gap-40px flex-wrap">
		<div><a href="/">A</a></div>
		<div>B</div>
		<div>C</div>
		<div>D</div>
		<div class="example gap-20px flex-wrap">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
		</div>
	</div>
</div>

<h4>Percentages</h4>

<pre>
.example
	display: flex;
	flex-wrap: wrap;
	gap: 3%;
}
</pre>

<div class="outline">
	<div class="example gap-3% flex-wrap">
		<div><a href="/">A</a></div>
		<div>B</div>
		<div>C</div>
		<div>D</div>
	</div>
</div>

<h4>Combination</h4>

<pre>
.example
	display: flex;
	flex-wrap: wrap;
	gap: 3%;
}
</pre>

<div class="outline">
	<div class="example gap-3% flex-wrap">
		<div><a href="/">A</a></div>
		<div>B</div>
		<div>C</div>
		<div>D</div>
		<div class="example gap-6% flex-wrap">
			<div>A</div>
			<div>B</div>
			<div>C</div>
			<div>D</div>
		</div>
	</div>
</div>
