<style>
	:root {
		--FI_has-gutters: true;
		--fl-row-gap: 0px;
		--fl-column-gap: 0px;
	}

	body {
		padding: 100px;
		font-family: sans-serif;
	}

	.example>* {
		box-sizing: border-box;
		background: yellow;

		border-radius: 2px;
		padding-top: 16px;
		padding-right: 16px;
		padding-bottom: 16px;
		padding-left: 16px;
		font-size: 13px;
		font-weight: bold;
	}

	.example>.example>* {
		background: pink;

	}

	.example>.example>.example>* {
		background: aqua;
	}

	.example>.example>.example>.example>* {
		background: lightgrey;
	}

	.example>.example {
		background: transparent;
		padding: 0;
	}

	.example>.example>.example {
		background: transparent;
		padding: 0;
	}
</style>

<h4>No width</h4>
<div class="boundary">
	<div class="example" style="
	display: flex;
	gap: 20px;
	">
		<div><a href="/">A</a></div>
		<div>B</div>
		<div>C</div>
		<div>D</div>
		<div>E</div>
		<div>F</div>
		<div>G</div>
		<div>H</div>
		<div>I</div>
		<div>J</div>
		<div>K</div>
		<div>L</div>
		<div>M</div>
		<div>N</div>
		<div>O</div>
		<div>P</div>
		<div>Q</div>
	</div>
</div>
